// transcriptions types
export const LOAD_TRANSCRIPTIONS = 'LOAD_TRANSCRIPTIONS'
export const LOAD_TRANSCRIPTIONS_SUCCESS = 'LOAD_TRANSCRIPTIONS_SUCCESS'
export const LOAD_TRANSCRIPTIONS_FAILED = 'LOAD_TRANSCRIPTIONS_FAILED'
